# -*- coding: utf-8 -*-
"""CS246 - Colab 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hsUcHynaFy4AaVFuoOjZl6EGf7GoDEAE

# CS246 - Colab 5
## PageRank

### Setup

First of all, we authenticate a Google Drive client to download the dataset we will be processing in this Colab.

**Make sure to follow the interactive instructions.**
"""

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

id='1EoolSK32_U74I4FeLox88iuUB_SUUYsI'
downloaded = drive.CreateFile({'id': id})
downloaded.GetContentFile('web-Stanford.txt')

"""If you executed the cells above, you should be able to see the dataset we will use for this Colab under the "Files" tab on the left panel.

Next, we import some of the common libraries needed for our task.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

"""### Data Loading

For this Colab we will be using [NetworkX](https://networkx.github.io), a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.

The dataset we will analyze is a snapshot of the Web Graph centered around [stanford.edu](https://stanford.edu), collected in 2002. Nodes represent pages from Stanford University (stanford.edu) and directed edges represent hyperlinks between them. [[More Info]](http://snap.stanford.edu/data/web-Stanford.html)
"""

import networkx as nx

G = nx.read_edgelist('web-Stanford.txt', create_using=nx.DiGraph)

print(nx.info(G))

"""### Your Task

To begin with, let's simplify our analysis by ignoring the dangling nodes and the disconnected components in the original graph.

Use NetworkX to identify the **largest** weakly connected component in the ```G``` graph.  From now on, use this connected component for all the following tasks.
"""

# YOUR CODE HERE
LWCC_nodes_list = max(nx.weakly_connected_components(G), key=len)
LWCC = G.subgraph(LWCC_nodes_list)
print(nx.info(LWCC))

"""Compute the PageRank vector, using the default parameters in NetworkX: [https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.link_analysis.pagerank_alg.pagerank.html#networkx.algorithms.link_analysis.pagerank_alg.pageranky](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.link_analysis.pagerank_alg.pagerank.html#networkx.algorithms.link_analysis.pagerank_alg.pagerank)"""

# YOUR CODE HERE
pr = nx.pagerank(LWCC)

"""In 1999, Barabási and Albert proposed an elegant mathematical model which can generate graphs with topological properties similar to the Web Graph (also called Scale-free Networks).

If you complete the steps below, you should obtain some empirical evidence that the Random Graph model is inferior compared to the Barabási–Albert model when it comes to generating a graph resembling the World Wide Web!

As such, we will use two different graph generator methods, and then we will test how well they approximate the Web Graph structure by means of comparing the respective PageRank vectors. [[NetworkX Graph generators]](https://networkx.github.io/documentation/stable/reference/generators.html#)

Using for both methods ```seed = 1```, generate:


1.   a random graph (with the fast method), setting ```n``` equal to the number of nodes in the original connected component, and ```p = 0.00008```
2.   a Barabasi-Albert graph (with the standard method), setting ```n``` equal to the number of nodes in the original connected component, and finding the right ***integer*** value for ```m``` such as the resulting number of edges **approximates by excess** the number of edges in the original connected component

and compute the PageRank vectors for both graphs.
"""

# YOUR CODE HERE
random_graph = nx.fast_gnp_random_graph(255265, p = 0.00008, seed = 1)
pr_random_graph = nx.pagerank(random_graph)
print(nx.info(random_graph))

BA_graph = nx.barabasi_albert_graph(n = 255265, m = 9, seed = 1)
pr_BA_graph = nx.pagerank(BA_graph)
print(nx.info(BA_graph))

sorted_pr_random_graph = sorted(pr_random_graph.items(), key=lambda x: -x[1])
sorted_pr_BA_graph = sorted(pr_BA_graph.items(), key=lambda x: -x[1])

list_sorted_pr_random_graph = list(sorted_pr_random_graph)
list_sorted_pr_BA_graph = list(sorted_pr_BA_graph)
print(list_sorted_pr_random_graph[0])
print(list_sorted_pr_BA_graph[0])

"""Compare the PageRank vectors obtained on the generated graphs with the PageRank vector you computed on the original connected component.
**Sort** the components of each vector by value, and use cosine similarity as similarity measure. 

Feel free to use any implementation of the cosine similarity available in third-party libraries, or implement your own with ```numpy```.
"""

# YOUR CODE HERE
list_sorted_pr_LWCC_vector = np.array(sorted(pr.values(), key = lambda x: -x)).reshape((1, -1))
list_sorted_pr_random_graph_vector = np.array(sorted(pr_random_graph.values(), key = lambda x: -x)).reshape((1, -1))
list_sorted_pr_BA_graph_vector = np.array(sorted(pr_BA_graph.values(), key = lambda x: -x)).reshape((1, -1))

from sklearn.metrics.pairwise import cosine_similarity
cos_sim_LWCC_random = cosine_similarity(list_sorted_pr_LWCC_vector, list_sorted_pr_random_graph_vector)
cos_sim_LWCC_BA = cosine_similarity(list_sorted_pr_LWCC_vector, list_sorted_pr_BA_graph_vector)

print("Cosine similarity between the web-Stanford graph and the random generated graph: {}".format(cos_sim_LWCC_random))
print("cosine similarity between the web-Stanford graph and the Barabási-Albert graph: {}".format(cos_sim_LWCC_BA))

"""Once you have working code for each cell above, **head over to Gradescope, read carefully the questions, and submit your solution for this Colab**!"""